# Generated by Django 5.2.14 on 2026-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-created_at'], name='blog_post_is_publ_1d5edc_idx'),
        ),
    ]
